# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 didn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
key-mapping.preset = 'qwerty'

[mode.main.binding]
alt-cmd-enter = 'exec-and-forget open -n /Applications/iTerm.app'

alt-cmd-j = 'focus left'
alt-cmd-k = 'focus down'
alt-cmd-l = 'focus up'
alt-cmd-semicolon = 'focus right'

alt-cmd-shift-j = 'move left'
alt-cmd-shift-k = 'move down'
alt-cmd-shift-l = 'move up'
alt-cmd-shift-semicolon = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
alt-ctrl-h = 'split horizontal'
alt-ctrl-v = 'split vertical'

alt-ctrl-f = 'fullscreen'
alt-ctrl-s = 'layout v_accordion' # 'layout stacking' in i3
alt-ctrl-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-ctrl-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-cmd-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-cmd-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-cmd-a = 'focus parent'

alt-cmd-1 = 'workspace 1'
alt-cmd-2 = 'workspace 2'
alt-cmd-3 = 'workspace 3'
alt-cmd-4 = 'workspace 4'
alt-cmd-5 = 'workspace 5'
alt-cmd-6 = 'workspace 6'
alt-cmd-7 = 'workspace 7'
alt-cmd-8 = 'workspace 8'
alt-cmd-9 = 'workspace 9'
alt-cmd-0 = 'workspace 10'

alt-cmd-shift-1 = 'move-node-to-workspace 1'
alt-cmd-shift-2 = 'move-node-to-workspace 2'
alt-cmd-shift-3 = 'move-node-to-workspace 3'
alt-cmd-shift-4 = 'move-node-to-workspace 4'
alt-cmd-shift-5 = 'move-node-to-workspace 5'
alt-cmd-shift-6 = 'move-node-to-workspace 6'
alt-cmd-shift-7 = 'move-node-to-workspace 7'
alt-cmd-shift-8 = 'move-node-to-workspace 8'
alt-cmd-shift-9 = 'move-node-to-workspace 9'
alt-cmd-shift-0 = 'move-node-to-workspace 10'

alt-cmd-shift-c = 'reload-config'

alt-ctrl-right = 'focus-monitor --wrap-around next'
alt-ctrl-left = 'focus-monitor --wrap-around prev'
alt-ctrl-shift-right = 'move-workspace-to-monitor --wrap-around next'
alt-ctrl-shift-left = 'move-workspace-to-monitor --wrap-around prev'

alt-cmd-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

# Automations

[[on-window-detected]]
   if.app-id = 'com.google.Chrome'
   run = 'move-node-to-workspace 1'

[[on-window-detected]]
   if.app-id = 'com.microsoft.Powerpoint'
   run = 'move-node-to-workspace 9'

[[on-window-detected]]
   if.app-id = 'com.jetbrains.pycharm'
   run = 'move-node-to-workspace 4'

[[on-window-detected]]
   if.app-id = 'com.jetbrains.intellij'
   run = 'move-node-to-workspace 4'

[[on-window-detected]]
   if.app-id = 'com.tinyspeck.slackmacgap'
   run = 'move-node-to-workspace 2'

[[on-window-detected]]
   if.app-id = 'com.microsoft.Outlook'
   run = 'move-node-to-workspace 7'

[[on-window-detected]]
   if.app-id = 'md.obsidian'
   run = 'move-node-to-workspace 3'

[[on-window-detected]]
   if.app-id = 'com.microsoft.teams2'
   run = 'move-node-to-workspace 5'

[[on-window-detected]]
   if.app-id = 'com.googlecode.iterm2'
   run = 'move-node-to-workspace 8'

[[on-window-detected]]
   if.app-id = 'com.microsoft.Excel'
   run = 'move-node-to-workspace 9'

[[on-window-detected]]
   if.app-id = 'com.apple.MobileSMS'
   run = 'move-node-to-workspace 6'

[[on-window-detected]]
   if.app-id = 'com.spotify.client'
   run = 'move-node-to-workspace 10'

